sudo: required
services:
  - docker

#before_install:
#  - docker build -t ichih/api-test -f ./api/Dockerfie.dev ./api

script:
  #  - docker run -e CI=true USERNAME/react-test npm test
  - docker build -t ichih/bank-api ./api
  - docker exec ichih/bank-api go test -run ./...

#  - docker build -t ichih/bank-web ./web
#  - docker build -t ichih/bank-nginx ./nginx
#  - docker build -t ichih/bank-cronjob ./cronjob

after_success:
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker build -t ichih/bank-web ./web
  - docker build -t ichih/bank-nginx ./nginx
  - docker build -t ichih/bank-cronjob ./cronjob
#  - docker push ichih/bank-api
#  - docker push ichih/bank-web
#  - docker push ichih/bank-cronjob
#  - docker push ichih/bank-nginx

#deploy:
#  provider: elasticbeanstalk
#  region: "ap-northeast-1"
#  app: "bank"
#  env: "Bank-env-1"
#  bucket_name: "ichih-bank"
#  bucket_path: "docker-bank"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY