version: '3.1'

services:
  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: account
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    hostname: db

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data
    restart: always
    hostname: redis

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    hostname: mongo

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    hostname: nsqlookupd
    container_name: nsqlookupd

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
#    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    hostname: nsqd
    container_name: nsqd

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    hostname: nsqadmin
    container_name: nsqadmin


  mailer:
    build:
      context: ./mailer
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=account
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_PORT=3306
      - REDIS_HOST=redis
      - NSQ_HOST=nsqd
      - Frontend=http://localhost:4000
      - Secret=snEHRnqQbz117VIFhE8bmtwIDY80NLUZ

    restart: always
    hostname: mailer

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - web
    ports:
      - "80:80"
    restart: always
    hostname: nginx

  cronjob:
    build:
      context: ./cronjob
    container_name: cronjob
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=account
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_PORT=3306
    depends_on:
      - backend
    restart: always
    hostname: cronjob

  backend:
    build:
      context: ./api
    ports:
      - "4001:4001"
    depends_on:
      - web
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=account
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_PORT=3306
      - NSQ_HOST=nsqd
      - MONGODB_HOST=mongo

    restart: always
    hostname: backend

  web:
    build:
      context: ./web
    ports:
      - "4000:4000"
    depends_on:
      - db
      - mongo
    environment:
      - DB_HOST=db
      - DB_NAME=account
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_PORT=3306
      - API=http://localhost
      - MONGODB_HOST=mongo
    restart: always
    hostname: web

