# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  redis:
    restart: always
    container_name: redis
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - /data/redis-data